name: deployment-on-wabli-server
'on':
  repository_dispatch:
    types:
      - deploy
jobs:
  Deploy-the-code:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WABLI_SERVER_SSH_HOST }}
          username: ${{ secrets.WABLI_SERVER_SSH_USERNAME }}
          password: ${{ secrets.WABLI_SERVER_SSH_PASSWORD }}
          port: ${{ secrets.WABLI_SERVER_SSH_PORT }}
          script: >-
            ./wabli-applications/deploy.sh -b main -d laughing-invention -r
            https://github.com/wabliplatform/frontEnd-getAllListFirstPage.git
